platform :ios, ‘8.0’
target 'Biconome' do

pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'SDWebImage'
pod 'SDCycleScrollView'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'JSONModel'
pod 'YYModel'
pod 'YYWebImage'
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
pod 'FMDB'
pod 'TZImagePickerController'
pod 'UITableView+FDTemplateLayoutCell'
pod 'CHTCollectionViewWaterfallLayout'
pod 'pop'
pod 'Bugly'
#pod 'IQKeyboardManager'
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase/Analytics'
pod 'SocketRocket'
pod 'SWOAuthCode'
pod 'MJExtension'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMCShare/UI'
# 集成微信(精简版0.2M)
pod 'UMCShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMCShare/Social/ReducedQQ'

# 集成新浪微博(精简版1M)
pod 'UMCShare/Social/ReducedSina'

pod 'BaiduMapKit', '~> 2.10.0'
pod 'PYPhotoBrowser'

pod 'WebsocketStompKit', :git => 'https://github.com/rguldener/WebsocketStompKit.git'

end

